### PR TITLE
SOE-3196: Adding js changes for featured paragraph

### PR DESCRIPTION
**Pull request by minorwm**
# READY FOR REVIEW

# Summary
- SOE Featured paragraph type

# Needed By (Date)
- Sprint end

# Criticality
- Client is eagerly awaiting this for the release.

# Steps to Test
- checkout branch `7.x-1.x-SOE-3196`
- `drush fr stanford_paragraph_types -y --force`
- go to `block/add/stanford-featured-block` and create a featured block.
- play around with the image, video, and image with video make sure things look good.

screen shot 2018-09-13 at 10 54 37 am
screen shot 2018-09-13 at 10 54 45 am

Examples of the featured blocks:

Image only:
screen shot 2018-09-13 at 2 55 53 pm

Image and Video
screen shot 2018-09-13 at 2 55 47 pm

Video Only
screen shot 2018-09-13 at 2 56 00 pm

# Affects 
- SoE (School of Engineering website)

# Associated Issues and/or People
## Related JIRA ticket(s)
https://stanfordits.atlassian.net/browse/SOE-3196

## Related PRs
Requires: https://github.com/SU-SOE/stanford_bean_types/pull/13

## Folks to notify

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by boznik** [comment]
i need to click twice for the video to play with image overlay. is that expected?

**Comment by boznik** [comment]
the image is removed when i go from image only to video only. is that expected?

**Comment by minorwm** [comment]
@boznik Both of those are known bugs in the admin. These will be revisited after the release.

**Comment by boznik** [comment]
don't forget to enable stanford_bean_types_featured before the reverts

**Pull request merged**
